services:
  api:
    build:
      context: .
      dockerfile: DOCKERFILE
    container_name: cinelog_db
    environment:
      DATABASE_URL: postgresql://reviews_user:reviews_pass@postgres:5432/reviews_db
      TEST_DATABASE_URL: postgresql://reviews_user:reviews_pass@postgres:5432/reviews_db
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: reviews_db
    environment:
      POSTGRES_DB: reviews_db
      POSTGRES_USER: reviews_user
      POSTGRES_PASSWORD: reviews_pass
    ports:
      - "5432:5432"
    volumes:
      - cinelog_pgdata:/var/lib/postgresql/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reviews_user -d reviews_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  cinelog_pgdata:
